### ISSUE TITLE
Example of how to use this addon

### ISSUE THREAD

**Issue by DaviSena** [Gongreg/storybook-usage#3]
Hi,

I am using the Storrybook in my react-native app to create a components showcase and I want to use some addon to show to others devs the code pattern of how to implement these features in future screens.
I found and installed this addon but I do not understand how to describe de "usage text" that will appear in the Usage Addon tab. 

Do you have any project or example code to help me?

Thanks

**Comment by Gongreg** [comment]
Hello. Sadly I do not have an example project for this addon. But this addon should work automatically after you add it as a decorator.

You cannot write anything inside the usage addon itself, it takes the component that is being rendered and tries to create representation of it. If you want to add notes, there is @storybook/addon-ondevice-notes that you can try to use :)

**Comment by marclundgren** [comment]
> But this addon should work automatically after you add it as a decorator

@Gongreg do you have an example of how to do that? How would I populate my usage tab?
![image](https://user-images.githubusercontent.com/1154834/89940398-4bd1ad80-dbce-11ea-8d78-393b89682f4b.png)
